name: Pull Request

on: [pull_request]

jobs:
    test:
        strategy:
            matrix:
                version: ['1.56.0', 'stable', 'nightly']
        runs-on: [ubuntu-latest]
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
            - uses: Swatinem/rust-cache@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.version }}
                  profile: minimal
                  override: true
            - name: Test
              run: cargo test
            - name: Build
              run: cargo build --release
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy
            - uses: Swatinem/rust-cache@v2
            - uses: baptiste0928/cargo-install@v2
              with:
                  crate: cargo-make
            - run: cargo clippy --all-targets --all-features -- --deny warnings
    docs:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
            - run: cargo doc
    format:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: nightly
                  components: rustfmt
            - uses: Swatinem/rust-cache@v2
            - uses: baptiste0928/cargo-install@v2
              with:
                  crate: cargo-make
            - run: cargo make format
